name = "yongsheng-consulting"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "yongsheng-consulting"

[[d1_databases]]
binding = "DB"
database_name = "ticket-consulting"
database_id = "7cf769c6-cdbf-4a8d-ba80-9cc425394da4"
