"use client";

import { useState } from "react";
import type { Locale } from "@/lib/i18n";
import { ConsultationCallout, PageHero, SectionHeading } from "@/components/shared";
import { MorphingDialog, MorphingDialogClose, MorphingDialogContainer, MorphingDialogContent, MorphingDialogDescription, MorphingDialogImage, MorphingDialogTitle, MorphingDialogTrigger } from "@/components/core/morphing-dialog";
import { AnimatedGroup } from "@/components/core/animated-group";
import { Badge } from "@/components/ui";

const entries = [
  { type: "Traffic", zhType: "交通罚单", zh: "驾驶时使用手机 · 纽约州", en: "Cellphone use while driving · NY State", points: "5", insurance: "20%–30%", cost: "≈ $2,000 / 3 years", result: "处理成功", detailZh: "公开脱敏案例参考：驾驶时使用手机可能带来 5 分、保险费率上涨及三年综合成本影响。", detailEn: "Public anonymized case reference: cellphone use while driving may involve 5 points, insurance increases, and multi-year costs.", img: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=900&q=80" },
  { type: "Traffic", zhType: "交通罚单", zh: "未系安全带 · 布鲁克林", en: "Seatbelt violation · Brooklyn", points: "0–3", insurance: "0%–10%", cost: "$100–$800 / 3 years", result: "处理成功", detailZh: "公开脱敏案例参考：积分、保险与总成本取决于具体条款、驾驶记录和处理结果。", detailEn: "Public anonymized case reference: points, insurance, and cost depend on the citation, record, and outcome.", img: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=80" },
  { type: "Traffic", zhType: "交通罚单", zh: "违反交通信号 · 皇后区", en: "Traffic signal violation · Queens", points: "3", insurance: "10%–25%", cost: "$1,000–$2,500 / 3 years", result: "处理成功", detailZh: "公开脱敏案例参考：此类事项可能涉及积分、保险影响及后续驾驶记录问题。", detailEn: "Public anonymized case reference: this type of matter may affect points, insurance, and driving records.", img: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80" },
  { type: "Traffic", zhType: "交通罚单", zh: "无证驾驶 · 长岛", en: "Unlicensed operation · Long Island", points: "0", insurance: "10%–40%", cost: "$500–$3,000 / 3 years", result: "处理成功", detailZh: "公开脱敏案例参考：即使不一定产生积分，也可能影响保险与后续驾驶资格。", detailEn: "Public anonymized case reference: even where points may not apply, insurance and driving eligibility can be affected.", img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80" },
  { type: "Traffic", zhType: "交通罚单", zh: "未让行 · 皇后区", en: "Failure to yield · Queens", points: "3", insurance: "10%–25%", cost: "$1,000–$2,500 / 3 years", result: "处理成功", detailZh: "公开脱敏案例参考：应结合事故情况、证据和适用规则进行个案处理。", detailEn: "Public anonymized case reference: facts, evidence, and applicable rules must be assessed individually.", img: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80" },
  { type: "Traffic", zhType: "交通罚单", zh: "超速 · 纽约州", en: "Speeding · NY State", points: "3–11", insurance: "20%–50%", cost: "$1,500–$5,000 / 3 years", result: "处理成功", detailZh: "公开脱敏案例参考：潜在积分、保险及总成本通常与速度、条款和既往驾驶记录相关。", detailEn: "Public anonymized case reference: points, insurance, and costs often depend on speed, citation type, and driving history.", img: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=80" },
];

export default function Cases({ params }: { params: { locale: Locale } }) {
  const locale = params.locale; const zh = locale === "zh"; const [filter, setFilter] = useState("All");
  const tabs = zh ? [["All", "全部"], ["Traffic", "交通罚单"]] : [["All", "All"], ["Traffic", "Traffic tickets"]];
  return <><PageHero locale={locale} kicker="CASE RESULTS" title={zh ? "结果背后，是清晰策略与持续跟进。" : "Every result begins with strategy and follow-through."} description={zh ? "以下为公开脱敏案例的摘要参考；积分、保险与实际结果均须按个案资料独立评估。" : "The following are summaries of publicly available anonymized case references. Points, insurance, and outcomes require individual assessment."} image="https://images.unsplash.com/photo-1528747008803-d74e2f7e1a79?auto=format&fit=crop&w=1800&q=85"/>
    <section className="mx-auto max-w-6xl px-5 py-20"><SectionHeading kicker="SELECTED OUTCOMES" title={zh ? "案例展示" : "Case results"}/><div className="mt-8 flex flex-wrap gap-2">{tabs.map(([key, label]) => <button key={key} onClick={() => setFilter(key)} className={`pressable border px-4 py-2 text-sm font-semibold ${filter === key ? "border-[#0f2747] bg-[#0f2747] text-white" : "border-slate-200 bg-white text-slate-600 hover:border-blue-600"}`}>{label}</button>)}</div>
      <AnimatedGroup className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3" variants={{ container: { hidden: { opacity: 0 }, visible: { opacity: 1, transition: { staggerChildren: 0.05 } } }, item: { hidden: { opacity: 0, transform: "translateY(10px)" }, visible: { opacity: 1, transform: "translateY(0)", transition: { duration: 0.28, ease: [0.23, 1, 0.32, 1] } } } }}>{entries.filter(item => filter === "All" || item.type === filter).map(item => <CaseDialog key={item.en} item={item} zh={zh}/>)}</AnimatedGroup>
    </section><ConsultationCallout locale={locale}/></>;
}

function CaseDialog({ item, zh }: { item: typeof entries[number]; zh: boolean }) { const title = zh ? item.zh : item.en; const category = zh ? item.zhType : item.type; const summary = zh ? item.detailZh : item.detailEn; const metrics = [[zh ? "积分" : "Points", item.points], [zh ? "保险影响" : "Insurance", item.insurance], [zh ? "成本参考" : "Cost reference", item.cost]]; return <MorphingDialog transition={{ type: "spring", bounce: 0.05, duration: 0.25 }}><MorphingDialogTrigger className="case-card group w-full overflow-hidden border border-slate-200 bg-white text-left shadow-sm"><div className="relative"><MorphingDialogImage src={item.img} alt={title} className="case-card-image h-44 w-full object-cover"/><Badge className="absolute left-3 top-3 border-white/60 bg-white/90 text-[#0f2747] shadow-sm backdrop-blur-sm">{category}</Badge></div><div className="p-5"><MorphingDialogTitle className="font-bold text-[#0f2747]">{title}</MorphingDialogTitle><p className="mt-3 line-clamp-3 text-xs leading-5 text-slate-500">{summary}</p></div></MorphingDialogTrigger><MorphingDialogContainer><MorphingDialogContent className="relative max-h-[calc(100vh-2.5rem)] w-full max-w-lg overflow-y-auto bg-white shadow-2xl"><MorphingDialogImage src={item.img} alt={title} className="h-56 w-full object-cover"/><div className="p-7"><Badge>{category}</Badge><MorphingDialogTitle className="mt-3 text-2xl font-bold text-[#0f2747]">{title}</MorphingDialogTitle><MorphingDialogDescription className="mt-4 leading-7 text-slate-600"><p>{summary}</p><div className="mt-5 grid grid-cols-3 border border-slate-200">{metrics.map(([label, value]) => <div key={label} className="border-r border-slate-200 p-3 last:border-r-0"><p className="text-[11px] font-bold text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-[#0f2747]">{value}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">{zh ? "案例内容为公开脱敏信息的摘要，仅供一般参考，不构成法律意见或结果承诺。" : "This is a summary of publicly available anonymized information, for general reference only; it is not legal advice or a promise of outcome."}</p></MorphingDialogDescription></div><MorphingDialogClose/></MorphingDialogContent></MorphingDialogContainer></MorphingDialog>; }
