"use client";

import { use, useState, type InputHTMLAttributes } from "react";
import { ArrowUpRight, Clock3, Mail, MapPin, Phone, ShieldCheck } from "lucide-react";
import { getDictionary, type Locale } from "@/lib/i18n";
import { PageHero } from "@/components/shared";
import { Button, Card, Select } from "@/components/ui";
import { useContactSettings } from "@/components/contact-context";
import { phoneHref } from "@/lib/contact";

export default function Contact({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = use(params); const zh = locale === "zh"; const t = getDictionary(locale); const [sent, setSent] = useState(false); const contact = useContactSettings();
  const labels = zh ? ["您的姓名", "联系电话", "咨询类型", "请描述您的情况"] : ["Your name", "Phone number", "Consultation type", "Tell us about your situation"];
  const address = zh ? contact.address_zh : contact.address_en; const details = [[Mail, zh ? "电子邮箱" : "Email", contact.email, `mailto:${contact.email}`], [MapPin, zh ? "办公地址" : "Office", address, contact.map_url], [Clock3, zh ? "办公时间" : "Hours", zh ? contact.hours_zh : contact.hours_en, ""]] as const;
  return <><PageHero locale={locale} kicker="CONTACT" title={zh ? "从一次简单沟通开始。" : "Start with a simple conversation."} description={zh ? "告诉我们您的情况，我们会尽快联系您，协助判断下一步。" : "Tell us about your situation. We will be in touch to help clarify the next step."} image="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=85"/>
    <main className="bg-[#f4f4f4]"><section className="mx-auto grid max-w-6xl gap-8 px-5 py-16 md:py-20 lg:grid-cols-[1.08fr_.92fr] lg:items-stretch">
      <Card className="p-7 md:p-9"><p className="text-xs font-bold tracking-[.14em] text-[#8a7d51]">CONSULTATION REQUEST</p><h2 className="mt-3 text-2xl font-bold tracking-[-.025em] text-[#1a243f]">{zh ? "告诉我们您的情况" : "Tell us what happened"}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-600">{zh ? "请留下基本信息和您最关心的问题。提交后，我们会尽快与您联系；紧急或临近截止日期的事项，建议直接致电。" : "Leave the essentials and the question that matters most. We will be in touch soon; for urgent matters or approaching deadlines, please call directly."}</p><form className="mt-8" onSubmit={e => { e.preventDefault(); setSent(true); }}><div className="grid gap-5 sm:grid-cols-2"><Field label={labels[0]} required name="name" autoComplete="name"/><Field label={labels[1]} required name="phone" type="tel" autoComplete="tel"/><label className="grid gap-2 text-sm font-bold text-slate-700"><span>{labels[2]}</span><Select name="issue"><option>{zh ? "交通罚单处理" : "Traffic ticket"}</option><option>{zh ? "移民咨询服务" : "Immigration services"}</option><option>E-ZPass</option><option>{zh ? "车祸理赔" : "Accident claim"}</option><option>{zh ? "信用修复" : "Credit repair"}</option></Select></label><Field label={zh ? "电子邮箱（可选）" : "Email (optional)"} name="email" type="email" autoComplete="email"/></div><label className="mt-5 grid gap-2 text-sm font-bold text-slate-700"><span>{labels[3]}</span><textarea required name="message" rows={5} className="resize-none border border-slate-300 bg-white px-3 py-3 text-sm leading-6 outline-none transition focus:border-[#8a7d51] focus:ring-2 focus:ring-[#d9d1b5]"/></label><Button className="mt-6 w-full">{sent ? t.formSent : t.consult}</Button>{sent && <p role="status" className="mt-4 flex items-center gap-2 text-sm font-semibold text-emerald-700"><ShieldCheck size={17}/>{zh ? "感谢您的提交，我们将尽快与您联系。" : "Thank you. We will be in touch shortly."}</p>}<p className="mt-5 flex gap-2 text-xs leading-5 text-slate-500"><ShieldCheck size={15} className="mt-0.5 shrink-0 text-[#8a7d51]"/>{zh ? "请勿通过表单发送敏感身份资料或完整财务信息。" : "Please do not send sensitive identity documents or complete financial information through this form."}</p></form></Card>
      <div className="grid min-h-[590px] grid-rows-[auto_1fr] gap-5"><Card className="overflow-hidden"><div className="border-b border-slate-200 bg-[#f4f1e8] p-6"><p className="text-xs font-bold tracking-[.14em] text-[#8a7d51]">DIRECT CONTACT</p><h2 className="mt-2 text-lg font-bold text-[#1a243f]">{zh ? "更需要即时回应？" : "Need a faster response?"}</h2><a href={phoneHref(contact.phone)} className="pressable mt-4 inline-flex items-center gap-2 bg-[#1a243f] px-4 py-3 text-sm font-bold text-white hover:bg-[#273452]"><Phone size={16}/>{contact.phone}</a></div><div className="grid gap-5 p-6">{details.map(([Icon, title, value, href]) => <div key={title} className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center bg-[#f4f1e8] text-[#8a7d51]"><Icon size={18}/></span><div className="min-w-0"><p className="text-xs font-bold tracking-[.05em] text-slate-500">{title}</p>{href ? <a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined} className="mt-1 flex items-start gap-1 text-sm font-semibold leading-5 text-[#1a243f] hover:text-[#8a7d51]"><span>{value}</span>{href.startsWith("http") && <ArrowUpRight size={14} className="mt-0.5 shrink-0"/>}</a> : <p className="mt-1 text-sm font-semibold leading-5 text-[#1a243f]">{value}</p>}</div></div>)}</div></Card><Card className="relative min-h-[280px] overflow-hidden"><iframe title="YONG SHENG CONSULTNG location" src={contact.map_url} className="absolute inset-0 h-full w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></Card></div>
    </section></main></>;
}

function Field({ label, required = false, type = "text", ...props }: { label: string; required?: boolean; type?: string } & InputHTMLAttributes<HTMLInputElement>) { return <label className="grid gap-2 text-sm font-bold text-slate-700"><span>{label}</span><input required={required} type={type} className="border border-slate-300 bg-white px-3 py-3 text-sm font-normal outline-none transition focus:border-[#8a7d51] focus:ring-2 focus:ring-[#d9d1b5]" {...props}/></label>; }
