"use client";
import { useMemo, useState } from "react";
import { MapPin, CalendarDays } from "lucide-react";
import type { Locale } from "@/lib/i18n";
import type { PublicCase, Taxonomy } from "@/lib/content";
import { Badge, Select } from "@/components/ui";
import { AnimatedGroup } from "@/components/core/animated-group";
import { MorphingDialog,MorphingDialogClose,MorphingDialogContainer,MorphingDialogContent,MorphingDialogDescription,MorphingDialogImage,MorphingDialogTitle,MorphingDialogTrigger } from "@/components/core/morphing-dialog";

const fallback="https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1000&q=80";
export function CasesBrowser({locale,cases,taxonomy}:{locale:Locale;cases:PublicCase[];taxonomy:{categories:Taxonomy[];types:Taxonomy[];regions:Taxonomy[]}}) {
 const zh=locale==="zh", [category,setCategory]=useState(""), [type,setType]=useState(""), [region,setRegion]=useState("");
 const types=taxonomy.types.filter(x=>!category||x.category_id===category);
 const visible=useMemo(()=>cases.filter(x=>(!category||x.category_id===category)&&(!type||x.type_id===type)&&(!region||x.region_id===region)),[cases,category,type,region]);
 return <section className="mx-auto max-w-6xl px-5 py-16 sm:py-20"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold tracking-[.14em] text-blue-600">SELECTED MATTERS</p><h2 className="mt-2 text-3xl font-bold tracking-[-.04em] text-[#0f2747]">{zh?"案例资料库":"Case library"}</h2><p className="mt-2 text-sm text-slate-500">{zh?`共 ${visible.length} 个公开脱敏案例`:`${visible.length} anonymized cases`}</p></div><div className="grid gap-2 sm:grid-cols-3 md:w-[620px]"><Select aria-label={zh?"大类":"Category"} value={category} onChange={e=>{setCategory(e.target.value);setType("")}}><option value="">{zh?"全部大类":"All categories"}</option>{taxonomy.categories.map(x=><option key={x.id} value={x.id}>{zh?x.name_zh:x.name_en}</option>)}</Select><Select aria-label={zh?"罚单类型":"Ticket type"} value={type} onChange={e=>setType(e.target.value)}><option value="">{zh?"全部类型":"All types"}</option>{types.map(x=><option key={x.id} value={x.id}>{zh?x.name_zh:x.name_en}</option>)}</Select><Select aria-label={zh?"地区":"Region"} value={region} onChange={e=>setRegion(e.target.value)}><option value="">{zh?"全部地区":"All regions"}</option>{taxonomy.regions.map(x=><option key={x.id} value={x.id}>{zh?x.name_zh:x.name_en}</option>)}</Select></div></div>
 <AnimatedGroup key={`${category}-${type}-${region}`} className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3" variants={{container:{hidden:{},visible:{transition:{staggerChildren:.035}}},item:{hidden:{opacity:0,y:14},visible:{opacity:1,y:0,transition:{duration:.3,ease:[.23,1,.32,1]}}}}}>{visible.map(item=><CaseCard key={item.id} item={item} zh={zh}/>)}</AnimatedGroup>
 {!visible.length&&<div className="mt-8 border border-slate-200 bg-slate-50 px-6 py-12 text-center text-sm text-slate-500">{zh?"暂无符合筛选条件的案例。":"No cases match these filters."}</div>}</section>;
}
 function CaseCard({item,zh}:{item:PublicCase;zh:boolean}) { const title=zh?item.title_zh:item.title_en, summary=zh?item.summary_zh:item.summary_en, category=zh?item.category_name_zh:item.category_name_en, type=zh?item.type_name_zh:item.type_name_en, region=zh?item.region_name_zh:item.region_name_en, imageError=(event:React.SyntheticEvent<HTMLImageElement>)=>{event.currentTarget.src=fallback}; return <MorphingDialog transition={{type:"spring",bounce:.04,duration:.28}}><MorphingDialogTrigger className="case-card group w-full overflow-hidden border border-slate-200 bg-white text-left shadow-sm"><div className="relative"><MorphingDialogImage src={item.image_url||fallback} onError={imageError} alt={title} className="h-44 w-full object-cover"/><Badge className="absolute left-3 top-3 border-white/70 bg-white/90 text-[#0f2747] shadow-sm">{category||type}</Badge></div><div className="p-5"><MorphingDialogTitle className="font-bold leading-6 text-[#0f2747]">{title}</MorphingDialogTitle><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-slate-500">{type&&<span>{type}</span>}{region&&<span className="inline-flex items-center gap-1"><MapPin size={11}/>{region}</span>}</div><p className="mt-3 line-clamp-3 text-xs leading-5 text-slate-500">{summary}</p></div></MorphingDialogTrigger><MorphingDialogContainer><MorphingDialogContent className="relative max-h-[calc(100dvh-2rem)] w-full max-w-xl overflow-y-auto overflow-x-hidden bg-white shadow-2xl"><MorphingDialogImage src={item.image_url||fallback} onError={imageError} alt={title} className="h-56 w-full object-cover"/><div className="p-6 sm:p-7"><div className="flex flex-wrap gap-2"><Badge>{category}</Badge>{type&&<Badge className="border-slate-200 bg-slate-50 text-slate-600">{type}</Badge>}</div><MorphingDialogTitle className="mt-3 text-2xl font-bold tracking-[-.03em] text-[#0f2747]">{title}</MorphingDialogTitle><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500">{region&&<span className="inline-flex items-center gap-1.5"><MapPin size={13}/>{region}</span>}{item.case_date&&<span className="inline-flex items-center gap-1.5"><CalendarDays size={13}/>{item.case_date}</span>}</div><MorphingDialogDescription className="mt-5 whitespace-pre-line text-sm leading-7 text-slate-600"><p>{zh?item.content_zh||summary:item.content_en||summary}</p><p className="mt-5 border-t border-slate-200 pt-4 text-xs leading-5 text-slate-500">{zh?"案例信息已脱敏，仅供一般参考，不构成法律建议或结果承诺。":"Anonymized case information is for general reference only and is not legal advice or a guarantee of outcome."}</p></MorphingDialogDescription></div><MorphingDialogClose/></MorphingDialogContent></MorphingDialogContainer></MorphingDialog>; }
