import { Car, Check, ClipboardCheck, CreditCard, MessageCircle, SearchCheck, ShieldCheck, Ticket } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { Locale } from "@/lib/i18n";
import { ConsultationCallout, PageHero, SectionHeading } from "@/components/shared";
import { Card } from "@/components/ui";

type Service = { icon: LucideIcon; zh: string; en: string; zhIntro: string; enIntro: string; zhPoints: string[]; enPoints: string[]; image: string };
const services: Service[] = [
  { icon: Ticket, zh: "行车罚单处理", en: "Traffic ticket resolution", zhIntro: "针对超速、闯红灯、违章停车及其他交通类罚单，协助您了解记录、时限与可行处理路径。", enIntro: "Support for speeding, red-light, parking, and other traffic tickets, with a clear review of records, deadlines, and options.", zhPoints: ["核对罚单内容与关键时间节点", "分析扣分、罚金与保险影响", "协助准备资料及后续处理安排"], enPoints: ["Review ticket details and key deadlines", "Assess points, fines, and insurance implications", "Prepare records and next-step arrangements"], image: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1100&q=85" },
  { icon: CreditCard, zh: "E-ZPass 豁免与管理", en: "E-ZPass disputes & management", zhIntro: "面对异常通行费、高额滞纳金或账户追缴时，我们协助厘清记录并建立有据可循的处理方案。", enIntro: "For disputed tolls, high late fees, or collections, we help clarify account records and develop a documented response.", zhPoints: ["梳理账户、通行记录与通知文件", "识别重复收费或异常项目", "协助申诉、减免与账户后续管理"], enPoints: ["Organize account, toll, and notice records", "Identify duplicate charges or anomalies", "Support appeals, relief requests, and account management"], image: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1100&q=85" },
  { icon: Car, zh: "车祸理赔", en: "Car accident claims", zhIntro: "发生车祸后，理赔过程常涉及多方沟通。我们协助您把握资料、保险沟通与后续权益维护的关键环节。", enIntro: "Accident claims often involve several parties. We help organize records, insurer communication, and the key steps for protecting your interests.", zhPoints: ["整理事故、医疗及保险相关资料", "协助理解保险流程与沟通重点", "跟进处理节点，减少信息遗漏"], enPoints: ["Organize accident, medical, and insurance records", "Clarify insurer process and communication priorities", "Track milestones and prevent missing information"], image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1100&q=85" },
  { icon: ShieldCheck, zh: "信用修复与信用保护", en: "Credit repair & protection", zhIntro: "信用报告中的错误或历史问题可能影响租房、贷款和日常财务安排。我们帮助您系统地识别、处理与保护信用记录。", enIntro: "Errors or historical issues in a credit report can affect housing, financing, and everyday planning. We help identify, address, and protect your record.", zhPoints: ["审阅信用报告中的异常与争议项目", "制定优先级清晰的改善步骤", "建立持续的信用保护建议"], enPoints: ["Review report anomalies and disputed items", "Prioritize practical improvement steps", "Establish ongoing credit-protection practices"], image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1100&q=85" },
];

export default function Services({ params }: { params: { locale: Locale } }) {
  const locale = params.locale; const zh = locale === "zh";
  const process = [[MessageCircle, zh ? "初步沟通" : "Initial consultation", zh ? "说明您的情况、已有资料和重要时间节点。" : "Share your situation, available records, and key timing."], [SearchCheck, zh ? "资料评估" : "Record review", zh ? "梳理事实、文件与可能影响，确认处理重点。" : "Review facts, records, and implications to identify priorities."], [ClipboardCheck, zh ? "制定方案" : "A clear plan", zh ? "说明下一步、配合事项与后续进度安排。" : "Confirm next steps, needed input, and progress updates."]];
  return <><PageHero locale={locale} kicker="SERVICES" title={zh ? "针对关键问题，提供专业支持。" : "Professional support for pivotal matters."} description={zh ? "我们以务实、透明的方式梳理情况，帮助您理解选择并稳妥推进。" : "We clarify the situation, explain your options, and help move matters forward with care."} image="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1800&q=85"/>
    <section className="mx-auto max-w-6xl px-5 py-20"><SectionHeading kicker="WHAT WE HANDLE" title={zh ? "服务范围" : "Our areas of support"} description={zh ? "先理解服务内容，再决定是否需要进一步咨询。" : "Understand the service first, then decide whether a consultation is right for you."}/>
      <div className="mt-10 grid gap-6 lg:grid-cols-2">{services.map((service, i) => { const Icon = service.icon; const points = zh ? service.zhPoints : service.enPoints; return <Card key={service.en} className="stagger-card overflow-hidden"><div className="grid sm:grid-cols-[190px_1fr]"><img src={service.image} alt={zh ? service.zh : service.en} className="h-48 w-full object-cover sm:h-full"/><div className="p-6"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center bg-blue-50 text-blue-600"><Icon size={20}/></span><h2 className="min-w-0 text-xl font-bold leading-tight tracking-[-.02em] text-[#0f2747]">{zh ? service.zh : service.en}</h2></div><span className="shrink-0 text-xs font-bold text-slate-400">0{i + 1}</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{zh ? service.zhIntro : service.enIntro}</p><ul className="mt-5 grid gap-2">{points.map(point => <li key={point} className="flex gap-2 text-xs leading-5 text-slate-600"><Check size={15} className="mt-0.5 shrink-0 text-blue-600"/>{point}</li>)}</ul></div></div></Card>; })}</div>
    </section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-5 py-16"><div className="flex flex-col justify-between gap-6 md:flex-row"><SectionHeading kicker="HOW IT WORKS" title={zh ? "让流程简单、信息透明。" : "A simple, transparent process."}/><p className="max-w-sm text-sm leading-7 text-slate-600">{zh ? "我们会在合适的阶段解释进展与需要配合的事项，避免您在不确定中等待。" : "We explain progress and what we need from you at the right time, so you are never left guessing."}</p></div><div className="mt-10 grid gap-8 md:grid-cols-3">{process.map(([Icon, title, text], i) => <div key={title as string} className="border-l-2 border-blue-600 pl-5"><span className="text-xs font-bold text-slate-400">0{i + 1}</span><div className="mt-3 flex items-center gap-3"><Icon className="shrink-0 text-[#0f2747]" size={24}/><h3 className="font-bold text-[#0f2747]">{title as string}</h3></div><p className="mt-3 text-sm leading-6 text-slate-600">{text as string}</p></div>)}</div></div></section><ConsultationCallout locale={locale}/></>;
}
