import Link from "next/link";
import { ArrowUpRight, BookOpen, Scale, ShieldCheck } from "lucide-react";
import type { Locale } from "@/lib/i18n";
import { getGuides } from "@/lib/content";
import { PageHero, ConsultationCallout } from "@/components/shared";
import { Badge, Card } from "@/components/ui";
import { InView } from "@/components/core/in-view";

export const dynamic="force-dynamic";
export default async function GuidesPage({params}:{params:Promise<{locale:Locale}>}) { const {locale}=await params, zh=locale==="zh", guides=await getGuides(); return <><PageHero locale={locale} kicker="KNOWLEDGE CENTER" title={zh?"先理解风险，再决定下一步。":"Understand the risk before deciding what comes next."} description={zh?"围绕纽约交通罚单、法庭传票与 TLC 事项整理的实用知识。":"Practical information on New York traffic tickets, court summonses, and TLC matters."} image="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1800&q=85"/><section className="mx-auto max-w-6xl px-5 py-16 sm:py-20"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{guides.map((guide,index)=><InView key={guide.id} variants={{hidden:{opacity:0,y:18},visible:{opacity:1,y:0}}} transition={{duration:.3,delay:Math.min(index,5)*.035}}><Link href={`/${locale}/guides/${guide.slug}`} className="group block h-full"><Card className="h-full p-6 transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-md"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center bg-blue-50 text-blue-700"><BookOpen size={18}/></span><ArrowUpRight size={17} className="text-slate-400 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-blue-600"/></div><div className="mt-5 flex flex-wrap gap-2"><Badge>{zh?guide.category_name_zh:guide.category_name_en}</Badge>{guide.type_name_zh&&<Badge className="border-slate-200 bg-slate-50 text-slate-600">{zh?guide.type_name_zh:guide.type_name_en}</Badge>}</div><h2 className="mt-4 text-lg font-bold leading-7 tracking-[-.025em] text-[#0f2747]">{zh?guide.title_zh:guide.title_en}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-500">{zh?guide.summary_zh:guide.summary_en}</p></Card></Link></InView>)}</div>{!guides.length&&<Card className="p-10 text-center text-sm text-slate-500">{zh?"知识内容正在整理中。":"Guides are being prepared."}</Card>}<div className="mt-10 grid gap-4 border border-slate-200 bg-slate-50 p-6 sm:grid-cols-2"><p className="flex items-start gap-3 text-sm leading-6 text-slate-600"><Scale className="mt-0.5 shrink-0 text-blue-600" size={18}/>{zh?"内容用于帮助理解常见流程与风险，不替代持牌律师的个案法律意见。":"These materials explain common processes and risks; they do not replace case-specific advice from a licensed attorney."}</p><p className="flex items-start gap-3 text-sm leading-6 text-slate-600"><ShieldCheck className="mt-0.5 shrink-0 text-blue-600" size={18}/>{zh?"请始终以罚单、法院或主管机构列明的回应期限为准。":"Always follow the response deadline stated by the ticket, court, or responsible agency."}</p></div></section><ConsultationCallout locale={locale}/></>; }
